info:
  application:
    mounted: yes
quarkus:
  http:
    cors: true
    port: 8080
  swagger-ui:
    always-include: true
    path: '/swagger-ui.html'
  datasource:
    db-kind: mysql
    username: oss_mcip_v1
    jdbc:
      url: jdbc:mysql://host.docker.internal:3306/quarkus_jpa_example_v1?serverTimezone=UTC&useLegacyDatetimeCode=false'
  hibernate-orm:
    database:
      generation: drop-and-create
  log:
    level: INFO
